--- #YAML:1.0
module_name: Math-Factor
dist_version_from: lib/Math/Factor.pm
installdirs: site
requires:
    Exporter: 0
distribution_type: module
license: perl
dist_abstract: factorises integers and calculates matching multiplications.
dist_author: Steven Schubiger
